

CREATE DATABASE MOLECULAR_GASTRONOMYS;
GO

USE MOLECULAR_GASTRONOMYS;

CREATE TABLE tblMIXTURE_TYPE(
	MixtureTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MixtureTypeName VARCHAR(50) NOT NULL
	
);

GO

CREATE TABLE tblGEOGRAPHY(
	GeographyID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	GeographyName VARCHAR(50) NOT NULL
);

GO
CREATE TABLE tblINGREDIENT_TYPE(
	IngredientTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IngredientTypeName VARCHAR(50) NOT NULL
);

GO
CREATE TABLE tblFLAVOR(
	FlavorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FlavorName VARCHAR(50) NOT NULL
);

GO
CREATE TABLE tblCOMPOUND_TYPE(
	CompoundTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompoundTypeName VARCHAR(50) NOT NULL
);

GO
CREATE TABLE tblSENSATION(
	SensationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SensationName VARCHAR(50) NOT NULL,
	SensationDesc VARCHAR(250) NULL
);

GO
CREATE TABLE tblCOMPOSITE(
	CompositeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompositeName VARCHAR(50) NOT NULL,
	CompositeDesc VARCHAR(250) NULL,
	MixtureTypeID INT FOREIGN KEY REFERENCES tblMIXTURE_TYPE(MixtureTypeID) NOT NULL
);

GO


CREATE TABLE tblCOMPOUND(
	CompoundID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompoundName VARCHAR(50) NOT NULL,
	CompoundBoilingPoint DECIMAL NOT NULL,
	CompoundFreezingPoint DECIMAL NOT NULL,
	CompoundTypeID INT FOREIGN KEY REFERENCES tblCOMPOUND_TYPE(CompoundTypeID) NOT NULL,
	CompoundSensationID INT FOREIGN KEY REFERENCES tblSENSATION(SensationID) NULL,
	CompoundFlavorID INT FOREIGN KEY REFERENCES tblFLAVOR(FlavorID) NULL
);

GO

CREATE TABLE tblINGREDIENT(
	IngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IngredientName VARCHAR(50) NOT NULL,
	IngredientDesc VARCHAR(250) NULL,
	IngredientTypeID INT FOREIGN KEY REFERENCES tblINGREDIENT_TYPE(IngredientTypeID) NOT NULL
);

GO
CREATE TABLE tblCOMPOUND_PERCENTAGE
(
	CompoundPercentageID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompoundID INT FOREIGN KEY REFERENCES tblCOMPOUND(CompoundID),
	IngredientID INT FOREIGN KEY REFERENCES tblINGREDIENT(IngredientID),
	Percentage DECIMAL NOT NULL
);

GO
CREATE TABLE tblCOMPOSITE_INGREDIENT(
	CompositeIngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompositeID INT FOREIGN KEY REFERENCES tblCOMPOSITE(CompositeID),
	IngredientID INT FOREIGN KEY REFERENCES tblINGREDIENT(IngredientID)
);

GO
CREATE TABLE tblGEOGRAPHY_INGREDIENT(
	GeographyIngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	GeographyID INT FOREIGN KEY REFERENCES tblGEOGRAPHY(GeographyID),
	IngredientID INT FOREIGN KEY REFERENCES tblINGREDIENT(IngredientID)
);

GO
CREATE TABLE tblCOMPOUND_SENSATION(
	CompoundSensationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompoundID INT FOREIGN KEY REFERENCES tblCOMPOUND(CompoundID),
	SensationID INT FOREIGN KEY REFERENCES tblSENSATION(SensationID)
);

GO

CREATE TABLE tblCOMPOUND_FLAVOR(
	CompoundFlavorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompoundID INT FOREIGN KEY REFERENCES tblCOMPOUND(CompoundID),
	FlavorID INT FOREIGN KEY REFERENCES tblFLAVOR(FlavorID)
);

GO

